name: vds-react
services:
  app:
    build: .
    container_name: vds-react
    network_mode: bridge # to ensure localhost access to the API
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - $PWD:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - DOCKER_BUILDKIT=1
